Feat/search icon
gotitinc/aha pull request #13
Opened 2021-01-15 09:40 UTC by tinhvqbk

2021-01-16 11:03 UTC, namdaoduy requested changes

2021-01-16 11:03 UTC, namdaoduy commented on src/components/SideNav.js
> +              width={'700px'}
```suggestion
              width="700px"
```

2021-01-18 02:57 UTC, uendno approved these changes

2021-01-18 03:06 UTC, namdaoduy approved these changes

2021-01-18 03:06 UTC, merged